# generated by DipDup 8.1.1

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class PreviousInfoItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    list: List[str]


class TokensValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    current_cids: List[str]
    owner: str
    previous_info: List[PreviousInfoItem]
    price: str
    request: str
