# generated by DipDup 8.1.1

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TokensValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: str
    owner: str
