# generated by DipDup 8.1.1

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class OwnersInfoItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    list: List[str]


class SvlsValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    acceptRequest: bool
    owner: str
    owners_info: List[OwnersInfoItem]
    price: str
    request: str
